# Numpy Review Problem Set

In [ ]:
import numpy as np

#### Create an all zero numpy array of size 1000

In [ ]:
# write code here

#### Create a numpy array from all digits between [0,1000) that are divisible by five

In [ ]:
# write code here

#### Assign a 1 to every element divisible by 5 in the all zero array

In [ ]:
# write code here

#### Below is the grades for 6 students, convert to a numpy array

In [ ]:
grades = [90, 94, 88, 80, 78, 85]
# write code here

#### Scale every grade below 90 up by 2 points

In [ ]:
# write code here

#### Create a 10 by 10 matrix with 1 on the border 0 within the border

In [ ]:
# write code here

## Challenge Problems

#### Create an 10 by 10 checkerboard matrix in three lines of code.
Below is an example of a 3 by 3 checkerboard matrix

In [ ]:
# [0 1 0]
# [1 0 1]
# [0 1 0]

In [ ]:
# write code here

#### Assume that you have an MxM array, a, and a number, n (where n < M). Using array attributes and slicing, print out the nxn subarray at the center of a (example below for n=3, M=5   -- you may assume that n is odd and that a has an odd number of rows and columns) 

In [ ]:
#
# 0 0 0 0 0
# 0 X X X 0      X X X
# 0 X X X 0 ---> X X X
# 0 X X X 0      X X X
# 0 0 0 0 0

In [ ]:
# write code here