In [1]:
import numpy as np

### NumPy is the fundamental package for scientific computing with Python. Extremely useful!

 links used:
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html                        
http://bwsix.mit.edu/courses/course-v1:BWSI+BWSI120+Summer_2017/

### Basic Arrays: much like lists but stores data of same type

#### Array Creation

In [2]:
digits = np.arange(0, 10, 1)  # create an array from [0,10), counting by 1
digits

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
digits.ndim  # in numpy language dimensions = axis

1

In [4]:
digits_2D = digits.reshape(2,5) # same values, different shape
digits_2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
print(digits_2D.dtype)
digits_2D.ndim

int32


2

In [6]:
python_list = [2.3, 3.4, 4.5, 5.6, 6.7]
b = np.array(python_list)  # create array from python list
print(b.dtype)
b

float64


array([ 2.3,  3.4,  4.5,  5.6,  6.7])

In [7]:
np.zeros( (3,4) )  # create array of zeros, can also create array of ones, np.ones()

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
random_array = np.random.random((2,100))  # values [0,1)
print(random_array.shape)
random_array[0,50]

(2, 100)


0.7149574945950401

#### Array Manipulation

In [9]:
print("a before adding 2: ", digits)  # numpy language these are examples of broadcasting
digits += 2   # equivalent to a = a + 2
print("a after adding 2: ", digits)
digits **= 2
print("a after squaring: ", digits)

a before adding 2:  [0 1 2 3 4 5 6 7 8 9]
a after adding 2:  [ 2  3  4  5  6  7  8  9 10 11]
a after squaring:  [  4   9  16  25  36  49  64  81 100 121]


In [10]:
x = np.array([[0., 1., 2.],  # shape: (2, 3)
            [3., 4., 5]])
y = np.array([0.1, .5, 1.])   # shape: (3, )
x + y  # more nuanced example of broadcasting

array([[ 0.1,  1.5,  3. ],
       [ 3.1,  4.5,  6. ]])

In [11]:
print(random_array.min())
print(random_array.max())
print(random_array.mean())

0.00320050393503
0.99652089868
0.486841126519


In [12]:
array = np.arange(16).reshape(2,2,2,2)
print(array.shape) 
print(array.ndim)  
print("\n")
array = array.reshape(4,4)
print(array.shape) 
print(array.ndim)  # notice the number of dimensions (axis) equals number of digits in reshape
array

(2, 2, 2, 2)
4


(4, 4)
2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
# .sum(axis=n) dimension n is collapsed 
# and all values in the new matrix equal to the sum of the corresponding collapsed values
cols_sum = array.sum(axis=0)
print("sum of columns:", cols_sum)
rows_sum = array.sum(axis=1)
print("sum of rows:", rows_sum)

sum of columns: [24 28 32 36]
sum of rows: [ 6 22 38 54]


Be aware there are several other common built in functions not shown in this tutorial.                                                           
I.E)   
np.sqrt(B)                           
A.dot(B) 

### Indexing & Slicing

In [14]:
a = np.arange(10)
print(a)
a[2]  # index like a python list

[0 1 2 3 4 5 6 7 8 9]


2

#### Slicing
basic format:   i:j:k where i is the starting index, j is the stopping index, and k is the step

In [15]:
print(a)
print(a[1:7:2])  # start at index 1, stop at index < 7, 2 steps at a time
print(a[slice(1,7,2)]) 

[0 1 2 3 4 5 6 7 8 9]
[1 3 5]
[1 3 5]


In [16]:
B = np.arange(16).reshape(4,4)
print((B))
B[2,3]  # index multidimensional arrays with a comma

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


11

In [17]:
print(B, "\n")
print(B[0:2,:], "\n")  #  index first 2 rows
print(B[slice(0,2, None),slice(None, None, None)])  #  index first 2 rows

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1 2 3]
 [4 5 6 7]]


In [18]:
print(a)
third_val = a[2:3]  # note that basic indexing returns a view of the same data (not a copy)
print("third_val initially: ", third_val)
a[2] = -1
print("array after changing third_val: ", a)  
print("third_val: ", third_val)  # why do you think basic indexing returns a view?

[0 1 2 3 4 5 6 7 8 9]
third_val initially:  [2]
array after changing third_val:  [ 0  1 -1  3  4  5  6  7  8  9]
third_val:  [-1]


### Advanced Indexing

#### Numpy array triggers advanced indexing

In [19]:
print(a)
indices = np.array([0,1,2,3])
a[indices]

[ 0  1 -1  3  4  5  6  7  8  9]


array([ 0,  1, -1,  3])

#### Boolean values trigger advanced indexing

In [20]:
print(a)
boolean = a < 6
a[boolean]

[ 0  1 -1  3  4  5  6  7  8  9]


array([ 0,  1, -1,  3,  4,  5])

#### Non-tuple sequence (e.g. list) of integers or boolean values

In [21]:
indices = list(indices)
a[indices]

array([ 0,  1, -1,  3])

Tuple containing at least one other sequence object (e.g. tuple, list) or NumPy array   
example: x[np.array([0]), 0, 1], x[(0, 1), (0, 2)]

#### Advanced Indexing: Copy

In [22]:
x = a[indices]  # advanced indexing creates a copy when its on the right side of an assignment 
x
a[indices] = -5
print(a)
print(x)

[-5 -5 -5 -5  4  5  6  7  8  9]
[ 0  1 -1  3]


In [23]:
last_two_indices = [-1,-2]  # negative numbers mean you start indexing from the left (end of array)
a[last_two_indices] = 10  # advanced indexing on left broadcast-updates an array (same as view)
a

array([-5, -5, -5, -5,  4,  5,  6,  7, 10, 10])