# Numpy Review Problem Set

In [3]:
import numpy as np

#### Create an all zero numpy array of size 1000

In [5]:
all_zeros = np.zeros((1000))
all_zeros.shape

(1000,)

#### Create a numpy array from all digits between [0,1000) that are divisible by five

In [10]:
digits_5 = np.arange(0,1000,5)

#### Assign a 1 to every element divisible by 5 in the all zero array

In [17]:
all_zeros[digits_5] = 1
all_zeros[105:116]

array([ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.])

#### Below is the grades for 6 students, convert to a numpy array

In [19]:
grades = [90, 94, 88, 80, 78, 85]
grades = np.array(grades)
grades

array([90, 94, 88, 80, 78, 85])

#### Scale every grade below 90 up by 2 points

In [20]:
below_90 = grades < 90
grades[below_90]

array([88, 80, 78, 85])

#### Create a 10 by 10 matrix with 1 on the border 0 within the border

In [21]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

## Challenge Problems

#### Create an 10 by 10 checkerboard matrix in three lines of code.
Below is an example of a 3 by 3 checkerboard matrix

In [ ]:
# [0 1 0]
# [1 0 1]
# [0 1 0]

In [45]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Assume that you have an MxM array, a, and a number, n (where n < M). Using array attributes and slicing, print out the nxn subarray at the center of a (example below for n=3, M=5-- you may assume that n is odd and that a has an odd number of rows and columns) 

In [9]:
#
# 0 0 0 0 0
# 0 X X X 0      X X X
# 0 X X X 0 ---> X X X
# 0 X X X 0      X X X
# 0 0 0 0 0

In [36]:
M = 5
n = 3
a = np.arange(25).reshape((5,5))
print(a)
start = (M-n)//2 # '//' does integer-division, M-n is the size on outside of x's, divide that by 2 is the start
stop = M - start
ans = a[start:stop, start:stop]
ans

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])